const countries = [
  { name: "Jordan", code: "JO", flag: "🇯🇴", phoneCode: "+962" },
  { name: "Afghanistan", code: "AF", flag: "🇦🇫", phoneCode: "+93" },
  { name: "Albania", code: "AL", flag: "🇦🇱", phoneCode: "+355" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿", phoneCode: "+213" },
  { name: "Argentina", code: "AR", flag: "🇦🇷", phoneCode: "+54" },
  { name: "Australia", code: "AU", flag: "🇦🇺", phoneCode: "+61" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", phoneCode: "+880" },
  { name: "Belgium", code: "BE", flag: "🇧🇪", phoneCode: "+32" },
  { name: "Brazil", code: "BR", flag: "🇧🇷", phoneCode: "+55" },
  { name: "Canada", code: "CA", flag: "🇨🇦", phoneCode: "+1" },
  { name: "China", code: "CN", flag: "🇨🇳", phoneCode: "+86" },
  { name: "Egypt", code: "EG", flag: "🇪🇬", phoneCode: "+20" },
  { name: "France", code: "FR", flag: "🇫🇷", phoneCode: "+33" },
  { name: "Germany", code: "DE", flag: "🇩🇪", phoneCode: "+49" },
  { name: "India", code: "IN", flag: "🇮🇳", phoneCode: "+91" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩", phoneCode: "+62" },
  { name: "Iran", code: "IR", flag: "🇮🇷", phoneCode: "+98" },
  { name: "Iraq", code: "IQ", flag: "🇮🇶", phoneCode: "+964" },
  { name: "Italy", code: "IT", flag: "🇮🇹", phoneCode: "+39" },
  { name: "Japan", code: "JP", flag: "🇯🇵", phoneCode: "+81" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾", phoneCode: "+60" },
  { name: "Mexico", code: "MX", flag: "🇲🇽", phoneCode: "+52" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱", phoneCode: "+31" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬", phoneCode: "+234" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰", phoneCode: "+92" },
  { name: "Philippines", code: "PH", flag: "🇵🇭", phoneCode: "+63" },
  { name: "Poland", code: "PL", flag: "🇵🇱", phoneCode: "+48" },
  { name: "Russia", code: "RU", flag: "🇷🇺", phoneCode: "+7" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦", phoneCode: "+966" },
  { name: "Singapore", code: "SG", flag: "🇸🇬", phoneCode: "+65" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦", phoneCode: "+27" },
  { name: "South Korea", code: "KR", flag: "🇰🇷", phoneCode: "+82" },
  { name: "Spain", code: "ES", flag: "🇪🇸", phoneCode: "+34" },
  { name: "Sweden", code: "SE", flag: "🇸🇪", phoneCode: "+46" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭", phoneCode: "+41" },
  { name: "Thailand", code: "TH", flag: "🇹🇭", phoneCode: "+66" },
  { name: "Turkey", code: "TR", flag: "🇹🇷", phoneCode: "+90" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦", phoneCode: "+380" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧", phoneCode: "+44" },
  { name: "United States", code: "US", flag: "🇺🇸", phoneCode: "+1" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳", phoneCode: "+84" },
];

export default countries;
